FROM node:22.19.0-alpine3.22

RUN addgroup -S broker && adduser -S -G broker broker
WORKDIR /app

COPY package.json package-lock.json meshctrl.js ./
RUN npm ci --omit=dev && npm cache clean --force

COPY commando/broker/server.mjs ./commando/broker/server.mjs
USER broker
ENTRYPOINT ["node", "/app/commando/broker/server.mjs"]
